config/routes.rb
Rails.application.routes.draw do
  get 'otp', to: 'sessions#otp'
  post 'verify_otp', to: 'sessions#verify_otp'
  resources :posts
  get 'home/index'
  devise_for :users

  post '/posts/:id/like', to: 'posts#like', as: 'like_post'
  root to: "home#index"
  get '/feeds', to: 'home#feed', as: 'home_feed'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/feed.rb
class Feed < ApplicationRecord
   belongs_to :posts
  end
  
  

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
has_many :feeds
has_many :likes
has_and_belongs_to_many  :liked_users, class_name:"User", source: :user

  enum post_type: {EveryOne:"EveryOne",OnlyMe:"OnlyMe",MyFriend:"MyFriend"}
  scope :exclude_specific_user_posts, ->(user_id) { where.not(user_id: user_id) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         validates :otp_secret, presence: true
  has_many :posts
  has_many :likes
  has_and_belongs_to_many :liked_posts, class_name: "Post", source: :post


  def generate_otp
    self.otp_secret = ROTP::Base32.random_base32
    save
  end

  def otp_valid?(code)
    totp = ROTP::TOTP.new(otp_secret)
    totp.verify(code)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :mobile_no, :email, :name] )
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
  def feed
    if user_signed_in?
      @posts = Post.all # Assuming 'Feed' is your model representing feeds
    specific_user_id = current_user.id 
    @every_one_posts = Post.EveryOne.exclude_specific_user_posts(specific_user_id)
    @feeds = [@posts, @every_one_posts].flatten.uniq
  else
    # Handle the case where there is no authenticated user
    # For example, redirect to the login page or show an error message
  end
  end

  def friend_posts
    @friend_posts = current_user.friends.flat.map do |friend|
      friend.posts.where(post_type: "MyFriend")
    end
    @feed = [posts, every_one_posts, @friend_posts].flatten.unqi
    
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]
  # GET /posts or /posts.json
  def index
    @posts = Post.all
    user_id = params[:user_id]
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit
     @post = Post.find(params[:id])
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def like
    @post.liked_users << current_user
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "Like.Feed.#{@post.id}",
          partial: 'posts/like_button',
          locals: { post: @post }
        )
      end
    end
  end
  
  def unlike
    @post.liked_users.delete(current_user)
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "Like.Feed.#{params[:post_id]}",
          partial: 'posts/like_button',
          locals: { post: @post }
        )
      end
    end
  end
  
private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      puts "sdfgh"
      @post = Post.find(params[:id])
    end
    

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :user_id, :post_type)
    end
  end   

app/controllers/sessions_controller.rb
# app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
      user = User.find_by(email: params[:email])
      if user&.authenticate(params[:password])
        user.generate_otp
        send_otp_email(user)
        redirect_to otp_path
      else
        flash[:error] = "Invalid email/password combination"
        render 'new'
      end
    end
  
    def verify_otp
      user = User.find_by(email: params[:email])
      if user && user.otp_valid?(params[:otp])
        log_in user
        redirect_to user
      else
        flash[:error] = "Invalid OTP"
        render 'otp'
      end
    end
  
    private
  
    def send_otp_email(user)
      # Use mail gem to send OTP via email
      # Example:
       mail = Mail.new do
         from    'sanskarr2308@gmail.com'
        to      user.email
        subject 'One Time Password'
        body    "Your OTP: #{user.otp_secret}"
      end
      mail.deliver
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def liked_user_ids(post)
        post.liked_users.pluck(:id)
      end
    def get_link_for_like_unlike(post)
        if liked_user_ids(post).include?(current_user.id)
            link_to "Unlike",unlike_post_path(post)
        else
            link_to "Like",like_post_path(post),data: {turbo_method: :get}
        end
    end
    def edit_dom_id(feed)
        "Edit_Feed_#{feed.id}" # Assuming 'feed' is the name of your model
      end
    def edit_dom_id(post)
        "Edit.Feed.#{post.id}"
    end
    def dom_id(post)
        "Feed.#{post.id}"
    end
    def like_dom_id(post)
        "Like.Feed.#{post.id}"
    end
end



  

app/views/home/feed.html.erb
<%link_to "Go for Feed", home_feed_path %>
<% if  @feeds.present? %>
  <% @feeds.each do |feed| %>
    <div>
      <%= turbo_frame_tag dom_id(feed) do %>
        <strong>Description:</strong> <%= feed.description %>
        <%= Post.post_types[feed.post_type] %>
        <div class="align-right">
          Created By: <%= feed.user.email %><br>
          Created At: <%= feed.created_at %>
        </div>
      <% end %>

      <%= turbo_frame_tag edit_dom_id(feed) do %>
       
          <%= link_to "Edit Post", edit_post_path(feed) %>
       
        <% end %>
    

      <%= turbo_frame_tag like_dom_id(feed) do %>
        <%= get_link_for_like_unlike(feed) %>
      <% end %>
    </div>
    <hr>
  <% end %>
<% else %>
  <p>No feeds available</p>
<% end %>

app/views/home/index.html.erb
<h1>Welcome to home page</h1>


<% if user_signed_in? %>
<h1>Username: <%= current_user.username %></h1>

<%= link_to 'Sign Out', destroy_user_session_path %>
<% else %>
  <%= link_to 'Sign In', new_user_session_path %>
<% end %>
<br>
<%= link_to "Posts",posts_path%>
<br>
<%= link_to "Feeds", home_feed_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= errors.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
  <%= form.label :post_type, style: "display: block" %>
  <%= form.select :post_type, Post.post_types.keys,{},class:'form-control'%>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= post.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= post.user_id %>
  </p>

  <p>
    <strong>Post type:</strong>
    <%= post.post_type %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>